version: '3.8'

services:
  games-admin-panel-backend:
    build:
      dockerfile: ./Dockerfile.backend
    container_name: LOCAL-games-admin-panel-backend
    environment:
      - ConnectionStrings__AdminDbContext=Host=games-admin-panel-db;Port=5432;Database=AdminPanel;Username=admin;Password=123;
      - Urls=http://0.0.0.0:80
    ports:
      - 5004:80
    depends_on:
      games-admin-panel-db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy

  games-admin-panel-db:
    build:
      dockerfile: ./Dockerfile.db
    container_name: LOCAL-games-admin-panel-db
    ports:
      - 5433:5432
    restart: always
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d AdminPanel" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

  redis:
    image: redis:alpine
    container_name: LOCAL-games-admin-panel-redis
    environment:
      - REDISCLI_AUTH=redisSecretPassword
      - REDIS_PASSWORD=redisSecretPassword
    command: sh -c "redis-server --requirepass $${REDIS_PASSWORD}"
    ports:
      - 6379:6379
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep '^PONG$'" ]
      interval: 5s
      timeout: 5s
      retries: 5

